version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     - run: docker login -u $DOCKER_USER -p $DOCKER_PASS

     # build the application image
     - run: |
         docker build -t souzabrunoftw/bitcointrade-prometheus-exporter:${CIRCLE_BUILD_NUM} .
         docker tag souzabrunoftw/bitcointrade-prometheus-exporter:${CIRCLE_BUILD_NUM} souzabrunoftw/bitcointrade-prometheus-exporter:latest

     # deploy the image
     - run: |
         docker push souzabrunoftw/bitcointrade-prometheus-exporter:${CIRCLE_BUILD_NUM}
         docker push souzabrunoftw/bitcointrade-prometheus-exporter:latest
