kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    app: bitcointrade-exporter
  name: bitcointrade-exporter
  namespace: bitcoin
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: bitcointrade-exporter
  template:
    metadata:
      labels:
        app: bitcointrade-exporter
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: 9101
    spec:
      containers:
      - name: bitcointrade-exporter
        image: souzabrunoftw/bitcointrade-prometheus-exporter:test
        ports:
        - containerPort: 9101
          protocol: TCP
        imagePullPolicy: "Always"
